version: "3.6"
services:
  # MinIO is an OSS self-hosted S3 compatible object storage platform (See: https://github.com/minio/minio)
  # It works with all standard S3 client libraries, and comes with an admin GUI to manage the stored files
  #
  # You can access the admin panel at http://localhost:9000/minio/login after starting the service
  #
  # (The "Access Key" is MINIO_ROOT_USER, and "Secret Key" is MINIO_ROOT_PASSWORD)
  # (So you can login with "minio:minio123" as credentials)
  #
  # It is used to generate presigned image upload/download urls for the frontend (this is done via Hasura Action REST API handlers in Next.js)
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: "server /data --console-address ':9001'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  hasura_ci_db_data: